import java.util.Vector;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author no
 */
public class GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    Vector<Lampa> lampi = new Vector<>();
    Vector<Prelungitor> prelungitoareExtra = new Vector<>();
    Vector<LampaSmartInterior> lampiSmartExtra = new Vector<>();
    public GUI2() {
        initComponents();
        initializeData();
    }
    
    
    private void initializeData() {
        lampi.add(new Lampa("Lampa tip A", (byte) 10, "Alb", "LED", "Philips"));
        lampi.add(new Lampa("Lampa tip B", (byte) 11, "Roz", "LED", "Samsung"));
        lampi.add(new Lampa("Lampa tip C", (byte) 12, "Verde", "LED", "Ikea"));
        lampi.add(new Lampa("Lampa tip D", (byte) 13, "Alb", "LED", "Philips"));
        lampi.add(new Lampa("Lampa tip E", (byte) 14, "Roz", "Incandescentă", "Samsung"));
        lampi.add(new Lampa("Lampa tip F", (byte) 15, "Verde", "Halogen", "Ikea"));
        lampi.add(new Lampa("Lampa tip G", (byte) 16, "Alb", "LED", "Philips"));
        lampi.add(new Lampa("Lampa tip H", (byte) 17, "Roz", "Neon", "Samsung"));
        lampi.add(new Lampa("Lampa tip I", (byte) 18, "Verde", "LED", "Ikea"));
        lampi.add(new Lampa("Lampa tip J", (byte) 19, "Alb", "Halogen", "Philips"));


        prelungitoareExtra.add(new Prelungitor(3, true, 10, "Prelungitor 1", (byte) 20, "Negru", "LED", "Marca 1", "Tip Stecher 1", true));
        prelungitoareExtra.add(new Prelungitor(4, false, 12, "Prelungitor 2", (byte) 22, "Alb", "Halogen", "Marca 2", "Tip Stecher 2", false));
        prelungitoareExtra.add(new Prelungitor(5, true, 15, "Prelungitor 3", (byte) 25, "Rosu", "Incandescent", "Marca 3", "Tip Stecher 3", true));
        prelungitoareExtra.add(new Prelungitor(6, false, 17, "Prelungitor 4", (byte) 27, "Verde", "LED", "Marca 4", "Tip Stecher 1", false));
        prelungitoareExtra.add(new Prelungitor(7, true, 20, "Prelungitor 5", (byte) 30, "Albastru", "LED", "Marca 5", "Tip Stecher 2", true));
        prelungitoareExtra.add(new Prelungitor(3, true, 18, "Prelungitor 6", (byte) 32, "Portocaliu", "LED", "Marca 6", "Tip Stecher 3", true));
        prelungitoareExtra.add(new Prelungitor(4, false, 14, "Prelungitor 7", (byte) 28, "Mov", "Halogen", "Marca 7", "Tip Stecher 1", false));
        prelungitoareExtra.add(new Prelungitor(5, true, 16, "Prelungitor 8", (byte) 35, "Roz", "LED", "Marca 8", "Tip Stecher 2", true));
        prelungitoareExtra.add(new Prelungitor(6, true, 11, "Prelungitor 9", (byte) 24, "Gri", "Halogen", "Marca 9", "Tip Stecher 3", true));
        prelungitoareExtra.add(new Prelungitor(7, false, 13, "Prelungitor 10", (byte) 29, "Maro", "LED", "Marca 10", "Tip Stecher 1", false));


        lampiSmartExtra.add(new LampaSmartInterior("Smart 1", (byte) 18, "Roșu", "LED", "Microsoft", true, false, "Perete", (byte) 8, "Microsoft"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 2", (byte) 20, "Albastru", "Halogen", "Apple", false, true, "Tavan", (byte) 10, "Apple"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 3", (byte) 22, "Galben", "LED", "Samsung", true, true, "Masă", (byte) 12, "Samsung"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 4", (byte) 24, "Verde", "Halogen", "Microsoft", false, false, "Tavan", (byte) 14, "Microsoft"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 5", (byte) 26, "Mov", "LED", "Apple", true, true, "Perete", (byte) 16, "Apple"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 6", (byte) 28, "Alb", "LED", "Samsung", true, false, "Masă", (byte) 18, "Samsung"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 7", (byte) 30, "Negru", "Halogen", "Microsoft", false, true, "Tavan", (byte) 20, "Microsoft"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 8", (byte) 32, "Gri", "LED", "Apple", true, true, "Perete", (byte) 22, "Apple"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 9", (byte) 34, "Portocaliu", "LED", "Samsung", true, false, "Masă", (byte) 24, "Samsung"));
        lampiSmartExtra.add(new LampaSmartInterior("Smart 10", (byte) 36, "Roz", "Halogen", "Microsoft", false, true, "Tavan", (byte) 26, "Microsoft"));


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCuloare = new javax.swing.JTextField();
        TextFieldMarca = new javax.swing.JTextField();
        TextFieldPutereMin = new javax.swing.JTextField();
        ButtonFiltrare = new javax.swing.JButton();
        TextFieldPutereMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldProducator = new javax.swing.JTextField();
        jComboBoxControlVocal = new javax.swing.JComboBox<>();
        jComboBoxWifi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNumarPrize = new javax.swing.JTextField();
        jTextFieldLungimeCablu = new javax.swing.JTextField();
        jTextFieldTipStecher = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lampa", "Lampa Smart Interior", "Prelungitor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lampa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("OPTIUNI FILTRARE");

        jLabel3.setText("Culoare");

        jLabel4.setText("Marca");

        jLabel5.setText("Putere");

        TextFieldCuloare.setText("culoare");
        TextFieldCuloare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCuloareActionPerformed(evt);
            }
        });

        TextFieldMarca.setText("marca");

        TextFieldPutereMin.setText("0");
        TextFieldPutereMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPutereMinActionPerformed(evt);
            }
        });

        ButtonFiltrare.setText("Filtrare");
        ButtonFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFiltrareActionPerformed(evt);
            }
        });

        TextFieldPutereMax.setText("0");
        TextFieldPutereMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPutereMaxActionPerformed(evt);
            }
        });

        jLabel6.setText("Min");

        jLabel7.setText("Max");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("LampaSmartInterior");

        jLabel9.setText("Control Vocal");

        jLabel10.setText("WiFi");

        jLabel11.setText("Producator");

        jTextFieldProducator.setText("producator");

        jComboBoxControlVocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        jComboBoxControlVocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxControlVocalActionPerformed(evt);
            }
        });

        jComboBoxWifi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        jComboBoxWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWifiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Prelungitor");

        jLabel13.setText("Numar Prize");

        jLabel14.setText("Lungime Cablu");

        jLabel16.setText("Tip Stecher");

        jTextFieldNumarPrize.setText("NrPrize");
        jTextFieldNumarPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumarPrizeActionPerformed(evt);
            }
        });

        jTextFieldLungimeCablu.setText("LungimeCablu");

        jTextFieldTipStecher.setText("TipStecher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextFieldPutereMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextFieldPutereMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextFieldCuloare, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldMarca, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(ButtonFiltrare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxControlVocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProducator, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTipStecher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLungimeCablu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumarPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextFieldCuloare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxControlVocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldPutereMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel11)
                                .addComponent(jTextFieldProducator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPutereMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonFiltrare)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldNumarPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldLungimeCablu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldTipStecher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cosmin", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Alex", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();
        jTextArea1.setText(""); // Goleste text area

        switch (selectedItem) {
            case "Lampa":
                for (Lampa lampa : lampi) {
                    jTextArea1.append(lampa.toString() + "\n");
                }
                break;
            case "Lampa Smart Interior":
                for (LampaSmartInterior smartLampa : lampiSmartExtra) {
                    jTextArea1.append(smartLampa.toString() + "\n");
                }
                break;
            case "Prelungitor":
                for (Prelungitor prelungitor : prelungitoareExtra) {
                    jTextArea1.append(prelungitor.toString() + "\n");
                }
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ButtonFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFiltrareActionPerformed
        // TODO add your handling code here:
                                                  
    // Preluam valorile de filtrare
    String culoare = TextFieldCuloare.getText().trim();
    String marca = TextFieldMarca.getText().trim();
    String putereMinText = TextFieldPutereMin.getText().trim();
    String putereMaxText = TextFieldPutereMax.getText().trim();
    
    String controlVocalText = (String) jComboBoxControlVocal.getSelectedItem();
    String wifiText = (String) jComboBoxWifi.getSelectedItem(); 
    String producator = jTextFieldProducator.getText().trim();
    
    String numarPrizeText = jTextFieldNumarPrize.getText().trim();
    String lungimeCabluText = jTextFieldLungimeCablu.getText().trim();
    String tipStecher = jTextFieldTipStecher.getText().trim();

    
    // Convertim valorile din ComboBox in Boolean
    Boolean controlVocal = controlVocalText == null ? null : Boolean.parseBoolean(controlVocalText);
    Boolean wifi = wifiText == null ? null : Boolean.parseBoolean(wifiText);
    
    // Nu mai stiu daca sunt importante
    Byte putereMin = putereMinText.isEmpty() ? null : Byte.parseByte(putereMinText);
    Byte putereMax = putereMaxText.isEmpty() ? null : Byte.parseByte(putereMaxText);
    
    // Combo Boxul ul care zice ce va fi filtrat
    String selectedCategory = (String) jComboBox1.getSelectedItem();
    
    // Empty the text area
    jTextArea1.setText("");  
    
    boolean foundMatch = false;  // Variabila pentru daca un rezultat e bun

    switch (selectedCategory) {
        case "Lampa":
            for (Lampa lampa : lampi) {
                boolean matchesCuloare = true;
                boolean matchesMarca = true;
                boolean matchesPutere = true;
                
                
                if (!culoare.isEmpty() && !lampa.getCuloare().equalsIgnoreCase(culoare)) {
                    matchesCuloare = false;
                }
                
                
                if (!marca.isEmpty() && !lampa.getMarca().equalsIgnoreCase(marca)) {
                    matchesMarca = false;
                }
                
                if (putereMin != null && lampa.getPutere() < putereMin) {
                    matchesPutere = false;
                }
                
                if (putereMax != null && lampa.getPutere() > putereMax) {
                    matchesPutere = false;
                }

                // daca totul e bine, afisare in text area
                if (matchesCuloare && matchesMarca && matchesPutere) {
                    jTextArea1.append(lampa.toString() + "\n");
                    foundMatch = true;
                }
            }
            break;
            
        case "Lampa Smart Interior":
             for (LampaSmartInterior smartLampa : lampiSmartExtra) {
                boolean matchesControlVocal = true;
                boolean matchesWifi = true;
                boolean matchesProducator = true;
                
                if (controlVocal != null && smartLampa.getControlVocal() != controlVocal) {
                    matchesControlVocal = false;
                }
                
                if (wifi != null && smartLampa.getWifi() != wifi) {
                    matchesWifi = false;
                }
                
                if (!producator.isEmpty() && !smartLampa.getProducator().equalsIgnoreCase(producator)) {
                    matchesProducator = false;
                }

                if (matchesControlVocal && matchesWifi && matchesProducator) {
                    jTextArea1.append(smartLampa.toString() + "\n");
                    foundMatch = true;
                }
            }
            break;
            
        case "Prelungitor":
        for (Prelungitor prelungitor : prelungitoareExtra) {
            boolean matchesNumarPrize = true;
            boolean matchesLungimeCablu = true;
            boolean matchesTipStecher = true;
            
            if (!numarPrizeText.isEmpty()) {
                int numarPrize = Integer.parseInt(numarPrizeText);
                if (prelungitor.getNumarPrize() != numarPrize) {
                    matchesNumarPrize = false;
                }
            }

            if (!lungimeCabluText.isEmpty()) {
                int lungimeCablu = Integer.parseInt(lungimeCabluText);
                if (prelungitor.getLungimeCablu() < lungimeCablu) {
                    matchesLungimeCablu = false;
                }
            }

            if (!tipStecher.isEmpty() && !prelungitor.getTipStecher().equalsIgnoreCase(tipStecher)) {
                matchesTipStecher = false;
            }

            if (matchesNumarPrize && matchesLungimeCablu && matchesTipStecher) {
                jTextArea1.append(prelungitor.toString() + "\n");
                foundMatch = true;
            }
        }
        break;
            
        default:
            jTextArea1.append("Nu exista produse de aceasta categorie!\n");
            break;
    }

    // Daca nu avem rezultat bun, afisam mesajul in text area
    if (!foundMatch) {
        jTextArea1.append("Nu au fost gasite produse care sa corespunda filtrelor.\n");
    }
    }//GEN-LAST:event_ButtonFiltrareActionPerformed

    private void TextFieldCuloareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCuloareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCuloareActionPerformed

    private void TextFieldPutereMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPutereMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPutereMinActionPerformed

    private void TextFieldPutereMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPutereMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPutereMaxActionPerformed

    private void jComboBoxControlVocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxControlVocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxControlVocalActionPerformed

    private void jComboBoxWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWifiActionPerformed

    private void jTextFieldNumarPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumarPrizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumarPrizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFiltrare;
    private javax.swing.JTextField TextFieldCuloare;
    private javax.swing.JTextField TextFieldMarca;
    private javax.swing.JTextField TextFieldPutereMax;
    private javax.swing.JTextField TextFieldPutereMin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxControlVocal;
    private javax.swing.JComboBox<String> jComboBoxWifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldLungimeCablu;
    private javax.swing.JTextField jTextFieldNumarPrize;
    private javax.swing.JTextField jTextFieldProducator;
    private javax.swing.JTextField jTextFieldTipStecher;
    // End of variables declaration//GEN-END:variables
}
